export const msg = {
	/*****************************************************************/
	/*                   Informações do SISTEMA                      */
	/*****************************************************************/
	nome_sistema: "SISTEMA",
	versao_sistema: "3.0",
	desc_sistema: "Descrição Completa do Sistema.", 
	dados_usuario: "Dados do Usuário",
	logo_sistema: "Logo SISTEMA",
	/*****************************************************************/
	sair: "Sair",
	sucesso: "Sucesso",
	erro: "Erro",
	error: "error",
	msg_login_invalido: "Login ou Senha estão inválidos!",
	//usuario: "Usuário",
	digite: "Digite",
	seu: "seu",
	sua: "sua",
	entrar: "Entrar",
	apoio: "Apoio",
	importacao: "Importação",	
	download: "Download",
	exportacao: "Exportação",
	exportacoes: "Exportações",
	parametrizacao: "Parametrização",
	informacoes:"Informações",
	basico: "Básico",
	basicas: "Básicas",
	comunica: "Comunica",
	estrategico: "Estratégico",
	planos:	"Planos",
	ranking: "Ranking",
	tipos: "Tipos",
	elemento: "Elemento",
	elementos: "Elementos",
	indicadores: "Indicadores",
	indicador: "Indicador",
	planejamento: "Planejamento",
	controle: "Controle",
	siplad: "SIPLAD",
	gerencial: "Gerencial",
	relatorio: "Relatório",
	relatorios: "Relatórios",
	extracao: "Extração",
	comrj: "COMRJ",
	singra: "SINGRA",
	gru: "GRU",
	data: "Data",
	cadastro: "Cadastro",
	do: "do",
	da: "da",
	cadastrado_com_sucesso: "cadastrado com sucesso!",
	alterado_com_sucesso: "alterado com sucesso!",
	excluido_com_sucesso: "excluído com sucesso!",
	erro_inserir: "Erro ao inserir!",
	erro_alterar: "Erro ao alterar!",
	erro_excluir: "Erro ao excluir!",
	info:"info",	
	success: "success",
	excluir:"Excluir",
	novo:"Novo",
	campo_obrigatorio: "é obrigatório!",
	email: "Email",
	vc_deseja_excluir: "Você realmente deseja excluir",
	vc_deseja_alterar: "Você realmente deseja alterar",
	o: "o",
	os: "os",
	codigo: "Código",
	login: "Login",	
	nome: "Nome",
	usuario: "Usu\u00E1rio",
	usuarios: "Usu\u00E1rios",
	cadastrados: "Cadastrados",
	acesso: "acesso",
	senha: "Senha",
	enviar: "Enviar",
	redirecionando: "Redirecionando",
	autenticar: "Autenticar",
	taxas: "Taxas",
	altcred: "AltCred",
	pedido: "Pedido",
	todos: "Todos",
	recurso: "recurso",
	classe: "classe",
	metodo: "m\u00E9todo",
	acao: "a\u00E7\u00E3o",
	mensagem: "mensagem",
	versao: "vers\u00E3o",
	sim: "Sim",
	nao: "N\u00E3o",
	ativar: "Ativar",
	inativar: "Inativar",
	ativo: "Ativo",
	filtro: "Filtro",
	alerta: "Alerta",
	inativo: "Inativo",
	elaborar: "elaborar",
	atividade: "Atividade",
	projeto: "Projeto",
	extrateto: "Extra-Teto",
	ativa: "Ativa",
	inativa: "Inativa",
	concluida: "Conclu\u00EDda",
	cancelada: "Cancelada",
	buscar : " Buscar",
	retomar : " Retomar",
	imprimir : " Imprimir",
	exportar : " Exportar",
	total : "Total",
	plano : " Plano",
	observacao: "Observa\u00E7\u00E3o",
	parecer: "Parecer",
	tipo: "Tipo",
	download : " Download",
	em_revisao : " Em Revis\u00E3o",
	em_execucao: "Em Execu\u00E7\u00E3o",
	incluir: "Incluir",
	alterar: "Alterar",
	consultar: "Consultar",
	salvar: "Salvar",
	terminar: "Terminar",
	reabrir: "Reabrir",
	atualizar: "Atualizar",
	cancelar: "Cancelar",
	filtrar: "Filtrar",
	retornar: "Retornar",
	voltar: "Voltar",
	todos: "Todos",
	tramitar: "Tramitar",
	executar: "Executar",
	historico: "Hist\u00F3rico",
	ok : "OK",
	upload: "upload",
	ajustar: "Ajustar",
	selecione: "Selecione",
	descricao: "Descri\u00E7\u00E3o",
	horas : "Horas",
	dias : "Dias",
	semanas : "Semanas",
	mes : "M\u00EAs",
	meses : "Meses",
	adicionar: "Adicionar",
	remover: "Remover",
	copiar : " Copiar",
	exercicio : " Exerc\u00EDcio",
	codigo : " C\u00F3digo",
	limpar: "Limpar",
	sigla: "Sigla",
	titulo: "T\u00EDtulo",
	categoria: "Categoria",
	detalhar: "Detalhar",
	acima_de: "Acima de",
	abaixo_de : " Abaixo de",
	igual_a: "Igual a",
	entre : "Entre",
	servico : "Servi\u00E7o",
	adiantamento : "Adiantamento",
	data : "Data",
	contestada : "Contestada",
	certificada : "Certificada",
	quitada: " Quitada",
	cancelada: " Cancelada",
	registrada : "Registrada",
	constestar : "Contestar",
	certificar : "Certificar",
	quitar: "Quitar",
	url: "URL",
	inicio : " In\u00EDcio",
	fim : " Fim",
	execucao: "Execu\u00E7\u00E3o",
	planejamento: "Planejamento",
	monitorada: "Monitorada",
	meta : " Meta",
	submeta : " SubMeta",
	fase : " Fase",
	desfazer: "Desfazer",
	interna: "Interna",
	externa: "Externa",
	motivo : " Motivo",
	informacoes : " Informa\u00E7\u00F5es",
	detalhes : " Detalhes",
	esforco: "Esfor\u00E7o",
	resultado: "Resultado",
	agendado: "Agendado",
	processando: "Processando",
	cancelado: "Cancelado",
	falha: "Falha",
	concluido : " Conclu\u00EDdo",
	manipular: "Manipular",
	batch : " Batch",
	credito : " Cr\u00E9dito",
	debito : " D\u00E9bito",
	devolver : " Devolver",
	resgatar : " Resgatar",
	desvincular : " Desvincular",
	orgao : " \u00D3rg\u00E3o",
	disponiveis: "Dispon\u00EDveis",
	selecionados: "Selecionados",
	modulo : " M\u00F3dulo",
	nacional : " Nacional",
	estrangeira : " Estrangeira",
	valores: "Valores",
	moeda: "Moeda",
	valor: "Valor",
	cambio: "C\u00E2mbio",
	operador : " Operador",	
};